### ISSUE TITLE
Ajouter la gestion des tokens

### ISSUE THREAD

**Issue by mdevoldere** [Bperomet/ExoWebTeleFormation#1]
**Ajouter la gestion des tokens de session.

Créer la table tokens : 

CREATE TABLE tokens (
    session_id INT PRIMARY KEY AUTO INCREMENT
    user_id INT,
    token TEXT,
    date_add DATETIME,
    date_expire DATETIME,
)

Pour accéder à l'api, l'utilisateur doit se connecter (/connection). Il reçoit en retour un token de session.**

Pour les autres routes de l'api, le token doit être fourni.

Exemples: 

POST api.bastien.fr/connection  
REPONSE: {"user_id": 1, "token": "6346548730e32443f8e9a1ac6db265ce736f05cd33ca01bd6703cb8cd7fecc8b"} {"error": "invalid credentials"}

APRES LA CONNEXION: 
GET api.bastien.fr/users?token=6346548730e32443f8e9a1ac6db265ce736f05cd33ca01bd6703cb8cd7fecc8b
REPONSE : {} (objet user)

GET api.bastien.fr/users/2?token=6346548730e32443f8e9a1ac6db265ce736f05cd33ca01bd6703cb8cd7fecc8b
REPONSE : {} (objet user)

Pour les requêtes en POST, le token est ajouté dans les données du POST.

**Comment by Bperomet** [comment]
Je m'occupes de cette demande

**Comment by Bperomet** [comment]
La table a était crée ainsi que le post connection
